<?php
/**
 * FactionSymbol
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * FactionSymbol Class Doc Comment
 *
 * @category Class
 * @description The symbol of the faction.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FactionSymbol
{
    /**
     * Possible values of this enum
     */
    public const COSMIC = 'COSMIC';

    public const VOID = 'VOID';

    public const GALACTIC = 'GALACTIC';

    public const QUANTUM = 'QUANTUM';

    public const DOMINION = 'DOMINION';

    public const ASTRO = 'ASTRO';

    public const CORSAIRS = 'CORSAIRS';

    public const OBSIDIAN = 'OBSIDIAN';

    public const AEGIS = 'AEGIS';

    public const UNITED = 'UNITED';

    public const SOLITARY = 'SOLITARY';

    public const COBALT = 'COBALT';

    public const OMEGA = 'OMEGA';

    public const _ECHO = 'ECHO';

    public const LORDS = 'LORDS';

    public const CULT = 'CULT';

    public const ANCIENTS = 'ANCIENTS';

    public const SHADOW = 'SHADOW';

    public const ETHEREAL = 'ETHEREAL';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::COSMIC,
            self::VOID,
            self::GALACTIC,
            self::QUANTUM,
            self::DOMINION,
            self::ASTRO,
            self::CORSAIRS,
            self::OBSIDIAN,
            self::AEGIS,
            self::UNITED,
            self::SOLITARY,
            self::COBALT,
            self::OMEGA,
            self::_ECHO,
            self::LORDS,
            self::CULT,
            self::ANCIENTS,
            self::SHADOW,
            self::ETHEREAL
        ];
    }
}


