<?php
/**
 * WaypointTraitSymbol
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * WaypointTraitSymbol Class Doc Comment
 *
 * @category Class
 * @description The unique identifier of the trait.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WaypointTraitSymbol
{
    /**
     * Possible values of this enum
     */
    public const UNCHARTED = 'UNCHARTED';

    public const UNDER_CONSTRUCTION = 'UNDER_CONSTRUCTION';

    public const MARKETPLACE = 'MARKETPLACE';

    public const SHIPYARD = 'SHIPYARD';

    public const OUTPOST = 'OUTPOST';

    public const SCATTERED_SETTLEMENTS = 'SCATTERED_SETTLEMENTS';

    public const SPRAWLING_CITIES = 'SPRAWLING_CITIES';

    public const MEGA_STRUCTURES = 'MEGA_STRUCTURES';

    public const PIRATE_BASE = 'PIRATE_BASE';

    public const OVERCROWDED = 'OVERCROWDED';

    public const HIGH_TECH = 'HIGH_TECH';

    public const CORRUPT = 'CORRUPT';

    public const BUREAUCRATIC = 'BUREAUCRATIC';

    public const TRADING_HUB = 'TRADING_HUB';

    public const INDUSTRIAL = 'INDUSTRIAL';

    public const BLACK_MARKET = 'BLACK_MARKET';

    public const RESEARCH_FACILITY = 'RESEARCH_FACILITY';

    public const MILITARY_BASE = 'MILITARY_BASE';

    public const SURVEILLANCE_OUTPOST = 'SURVEILLANCE_OUTPOST';

    public const EXPLORATION_OUTPOST = 'EXPLORATION_OUTPOST';

    public const MINERAL_DEPOSITS = 'MINERAL_DEPOSITS';

    public const COMMON_METAL_DEPOSITS = 'COMMON_METAL_DEPOSITS';

    public const PRECIOUS_METAL_DEPOSITS = 'PRECIOUS_METAL_DEPOSITS';

    public const RARE_METAL_DEPOSITS = 'RARE_METAL_DEPOSITS';

    public const METHANE_POOLS = 'METHANE_POOLS';

    public const ICE_CRYSTALS = 'ICE_CRYSTALS';

    public const EXPLOSIVE_GASES = 'EXPLOSIVE_GASES';

    public const STRONG_MAGNETOSPHERE = 'STRONG_MAGNETOSPHERE';

    public const VIBRANT_AURORAS = 'VIBRANT_AURORAS';

    public const SALT_FLATS = 'SALT_FLATS';

    public const CANYONS = 'CANYONS';

    public const PERPETUAL_DAYLIGHT = 'PERPETUAL_DAYLIGHT';

    public const PERPETUAL_OVERCAST = 'PERPETUAL_OVERCAST';

    public const DRY_SEABEDS = 'DRY_SEABEDS';

    public const MAGMA_SEAS = 'MAGMA_SEAS';

    public const SUPERVOLCANOES = 'SUPERVOLCANOES';

    public const ASH_CLOUDS = 'ASH_CLOUDS';

    public const VAST_RUINS = 'VAST_RUINS';

    public const MUTATED_FLORA = 'MUTATED_FLORA';

    public const TERRAFORMED = 'TERRAFORMED';

    public const EXTREME_TEMPERATURES = 'EXTREME_TEMPERATURES';

    public const EXTREME_PRESSURE = 'EXTREME_PRESSURE';

    public const DIVERSE_LIFE = 'DIVERSE_LIFE';

    public const SCARCE_LIFE = 'SCARCE_LIFE';

    public const FOSSILS = 'FOSSILS';

    public const WEAK_GRAVITY = 'WEAK_GRAVITY';

    public const STRONG_GRAVITY = 'STRONG_GRAVITY';

    public const CRUSHING_GRAVITY = 'CRUSHING_GRAVITY';

    public const TOXIC_ATMOSPHERE = 'TOXIC_ATMOSPHERE';

    public const CORROSIVE_ATMOSPHERE = 'CORROSIVE_ATMOSPHERE';

    public const BREATHABLE_ATMOSPHERE = 'BREATHABLE_ATMOSPHERE';

    public const THIN_ATMOSPHERE = 'THIN_ATMOSPHERE';

    public const JOVIAN = 'JOVIAN';

    public const ROCKY = 'ROCKY';

    public const VOLCANIC = 'VOLCANIC';

    public const FROZEN = 'FROZEN';

    public const SWAMP = 'SWAMP';

    public const BARREN = 'BARREN';

    public const TEMPERATE = 'TEMPERATE';

    public const JUNGLE = 'JUNGLE';

    public const OCEAN = 'OCEAN';

    public const RADIOACTIVE = 'RADIOACTIVE';

    public const MICRO_GRAVITY_ANOMALIES = 'MICRO_GRAVITY_ANOMALIES';

    public const DEBRIS_CLUSTER = 'DEBRIS_CLUSTER';

    public const DEEP_CRATERS = 'DEEP_CRATERS';

    public const SHALLOW_CRATERS = 'SHALLOW_CRATERS';

    public const UNSTABLE_COMPOSITION = 'UNSTABLE_COMPOSITION';

    public const HOLLOWED_INTERIOR = 'HOLLOWED_INTERIOR';

    public const STRIPPED = 'STRIPPED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNCHARTED,
            self::UNDER_CONSTRUCTION,
            self::MARKETPLACE,
            self::SHIPYARD,
            self::OUTPOST,
            self::SCATTERED_SETTLEMENTS,
            self::SPRAWLING_CITIES,
            self::MEGA_STRUCTURES,
            self::PIRATE_BASE,
            self::OVERCROWDED,
            self::HIGH_TECH,
            self::CORRUPT,
            self::BUREAUCRATIC,
            self::TRADING_HUB,
            self::INDUSTRIAL,
            self::BLACK_MARKET,
            self::RESEARCH_FACILITY,
            self::MILITARY_BASE,
            self::SURVEILLANCE_OUTPOST,
            self::EXPLORATION_OUTPOST,
            self::MINERAL_DEPOSITS,
            self::COMMON_METAL_DEPOSITS,
            self::PRECIOUS_METAL_DEPOSITS,
            self::RARE_METAL_DEPOSITS,
            self::METHANE_POOLS,
            self::ICE_CRYSTALS,
            self::EXPLOSIVE_GASES,
            self::STRONG_MAGNETOSPHERE,
            self::VIBRANT_AURORAS,
            self::SALT_FLATS,
            self::CANYONS,
            self::PERPETUAL_DAYLIGHT,
            self::PERPETUAL_OVERCAST,
            self::DRY_SEABEDS,
            self::MAGMA_SEAS,
            self::SUPERVOLCANOES,
            self::ASH_CLOUDS,
            self::VAST_RUINS,
            self::MUTATED_FLORA,
            self::TERRAFORMED,
            self::EXTREME_TEMPERATURES,
            self::EXTREME_PRESSURE,
            self::DIVERSE_LIFE,
            self::SCARCE_LIFE,
            self::FOSSILS,
            self::WEAK_GRAVITY,
            self::STRONG_GRAVITY,
            self::CRUSHING_GRAVITY,
            self::TOXIC_ATMOSPHERE,
            self::CORROSIVE_ATMOSPHERE,
            self::BREATHABLE_ATMOSPHERE,
            self::THIN_ATMOSPHERE,
            self::JOVIAN,
            self::ROCKY,
            self::VOLCANIC,
            self::FROZEN,
            self::SWAMP,
            self::BARREN,
            self::TEMPERATE,
            self::JUNGLE,
            self::OCEAN,
            self::RADIOACTIVE,
            self::MICRO_GRAVITY_ANOMALIES,
            self::DEBRIS_CLUSTER,
            self::DEEP_CRATERS,
            self::SHALLOW_CRATERS,
            self::UNSTABLE_COMPOSITION,
            self::HOLLOWED_INTERIOR,
            self::STRIPPED
        ];
    }
}


