<?php
/**
 * WaypointType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * WaypointType Class Doc Comment
 *
 * @category Class
 * @description The type of waypoint.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WaypointType
{
    /**
     * Possible values of this enum
     */
    public const PLANET = 'PLANET';

    public const GAS_GIANT = 'GAS_GIANT';

    public const MOON = 'MOON';

    public const ORBITAL_STATION = 'ORBITAL_STATION';

    public const JUMP_GATE = 'JUMP_GATE';

    public const ASTEROID_FIELD = 'ASTEROID_FIELD';

    public const ASTEROID = 'ASTEROID';

    public const ENGINEERED_ASTEROID = 'ENGINEERED_ASTEROID';

    public const ASTEROID_BASE = 'ASTEROID_BASE';

    public const NEBULA = 'NEBULA';

    public const DEBRIS_FIELD = 'DEBRIS_FIELD';

    public const GRAVITY_WELL = 'GRAVITY_WELL';

    public const ARTIFICIAL_GRAVITY_WELL = 'ARTIFICIAL_GRAVITY_WELL';

    public const FUEL_STATION = 'FUEL_STATION';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PLANET,
            self::GAS_GIANT,
            self::MOON,
            self::ORBITAL_STATION,
            self::JUMP_GATE,
            self::ASTEROID_FIELD,
            self::ASTEROID,
            self::ENGINEERED_ASTEROID,
            self::ASTEROID_BASE,
            self::NEBULA,
            self::DEBRIS_FIELD,
            self::GRAVITY_WELL,
            self::ARTIFICIAL_GRAVITY_WELL,
            self::FUEL_STATION
        ];
    }
}


